# Generated by Django 5.1.1 on 2024-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('action', models.CharField(choices=[('download', 'Download'), ('convert', 'Convert')], max_length=10)),
                ('quality', models.CharField(choices=[('best', 'Best'), ('worst', 'Worst')], max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
