# Generated by Django 5.1.1 on 2024-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_remove_videodownload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='file_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='quality',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='url',
            field=models.URLField(),
        ),
    ]
