# Generated by Django 5.1.1 on 2024-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_videodownload_file_path_alter_videodownload_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownload',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
