# Generated by Django 5.1.1 on 2024-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_alter_videodownload_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodownload',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='action',
            field=models.CharField(choices=[('download', 'Download'), ('convert', 'Convert')], max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='quality',
            field=models.CharField(choices=[('best', 'Best'), ('worst', 'Worst')], max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
