# Generated by Django 5.1.1 on 2024-09-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_remove_videodownload_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodownload',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='videodownload',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='quality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='url',
            field=models.URLField(),
        ),
    ]
